//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class basicdate_schedule
    {
        public int id { get; set; }
        public string exam { get; set; }
        public string start_date { get; set; }
        public string end_date { get; set; }
        public string state { get; set; }
        public string exam_type { get; set; }
        public string batch { get; set; }
    }
}
