//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class basicdata_users
    {
        public int id { get; set; }
        public string fullname { get; set; }
        public string email { get; set; }
        public Nullable<int> phone { get; set; }
        public string role { get; set; }
        public string status { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string log { get; set; }
        public string nic { get; set; }
    }
}
