//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class basicdata_student
    {
        public int Id { get; set; }
        public string regid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Nic { get; set; }
        public string Dob { get; set; }
        public string home_address { get; set; }
        public string Home_tell { get; set; }
        public string Staying_address { get; set; }
        public string Stay_home_tell { get; set; }
        public string Father_name { get; set; }
        public string Parents_contact { get; set; }
        public string Ol_School { get; set; }
        public string Al_school { get; set; }
        public string Ol_result { get; set; }
        public string JoinDate { get; set; }
        public string Batch { get; set; }
        public string Scholarship { get; set; }
        public string Gender { get; set; }
    }
}
