//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class basicdata_subject
    {
        public int subid { get; set; }
        public string subject { get; set; }
        public string teacher { get; set; }
        public string log { get; set; }
    }
}
