//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_examresults
    {
        public int id { get; set; }
        public string exam { get; set; }
        public string batch { get; set; }
        public string regid { get; set; }
        public Nullable<decimal> subject_1 { get; set; }
        public Nullable<decimal> subject_2 { get; set; }
        public Nullable<decimal> subject_3 { get; set; }
        public Nullable<decimal> English { get; set; }
        public Nullable<decimal> git { get; set; }
        public Nullable<decimal> total_marks { get; set; }
        public Nullable<decimal> average_marks { get; set; }
        public Nullable<int> rank { get; set; }
        public string avg_state { get; set; }
        public string exam_date { get; set; }
    }
}
