//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class data_attandance
    {
        public int id { get; set; }
        public string batch { get; set; }
        public string classdate { get; set; }
        public string regid { get; set; }
        public string intime { get; set; }
        public string attandance { get; set; }
    }
}
