//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_payment_summary
    {
        public int id { get; set; }
        public string feeschedule { get; set; }
        public string year { get; set; }
        public string batch { get; set; }
        public string regid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string payment { get; set; }
        public string amount { get; set; }
        public string payment_date { get; set; }
        public string Al_school { get; set; }
    }
}
