//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProAdmin
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_schoarshipstd_summary
    {
        public string regid { get; set; }
        public string Firstname { get; set; }
        public string Lastname { get; set; }
        public string Al_school { get; set; }
        public string Scholarship { get; set; }
        public string Batch { get; set; }
    }
}
