// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAdminWebVersion.Models;

namespace ProAdminWebVersion.Migrations
{
    [DbContext(typeof(ManageStudentDetailsContext))]
    [Migration("20200627061627_db up")]
    partial class dbup
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProAdminWebVersion.Models.BatchDetail", b =>
                {
                    b.Property<int>("batchid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("batch")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("log")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("batchid");

                    b.ToTable("BatchDetails");
                });

            modelBuilder.Entity("ProAdminWebVersion.Models.SchoolDetail", b =>
                {
                    b.Property<int>("schid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("log")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("schoolname")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("schid");

                    b.ToTable("SchoolDetails");
                });

            modelBuilder.Entity("ProAdminWebVersion.Models.StudentsDetail", b =>
                {
                    b.Property<int>("Sid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AlSchool")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Dob")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HomeAdress")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("HomeTell")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("JoinedDate")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nic")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OlResult")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("OlSchool")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ParentsTell")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RegId")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Scholership")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StayAddress")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("StayHomeTell")
                        .HasColumnType("varchar(200)");

                    b.HasKey("Sid");

                    b.ToTable("StudentDetails");
                });

            modelBuilder.Entity("ProAdminWebVersion.Models.SubjectDetail", b =>
                {
                    b.Property<int>("subid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("log")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("subject")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("teacher")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("subid");

                    b.ToTable("SubjectDetails");
                });

            modelBuilder.Entity("ProAdminWebVersion.Models.UniversityDetail", b =>
                {
                    b.Property<int>("uniid")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("log")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("uniname")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("uniid");

                    b.ToTable("UniversityDetails");
                });

            modelBuilder.Entity("ProAdminWebVersion.Models.UsersDetail", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("fullname")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("log")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("nic")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("role")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.HasKey("id");

                    b.ToTable("GetUsersDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
